name: Обработка Markdown файлов

on:
  schedule:
    - cron: '0 0 * * 1'  # Запуск каждый понедельник
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  process-markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Настройка Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
        
      - name: Создание директории docs если она не существует
        run: mkdir -p docs

      - name: Обработка Markdown файлов
        run: |
          # Находим все markdown файлы в src и подпапках
          echo "🔍 Поиск Markdown файлов в src/..."
          mkdir -p tmp_md
          
          # Обрабатываем каждый файл
          find src -type f -name "*.md" | while read file; do
            filename=$(basename "$file")
            echo "⚙️ Обработка файла: $file"
            
            # Проверяем и удаляем скриптовый блок в начале файла
            sed '/^<script lang="ts">$/,/^</script>$/d' "$file" > "tmp_md/$filename"
            
            # Копируем обработанный файл в целевую директорию
            cp "tmp_md/$filename" "docs/$filename"
            
            echo "✅ Файл сохранен как: docs/$filename"
          done
          
          # Удаляем временную директорию
          rm -rf tmp_md
          
      - name: Коммит и пуш изменений
        run: |
          # Проверяем, есть ли изменения
          if [[ -n $(git status -s docs/) ]]; then
            echo "💾 Сохранение изменений..."
            git add docs/
            git commit -m "Обновление обработанных Markdown файлов"
            git push origin HEAD:main
            echo "✅ Изменения успешно сохранены"
          else
            echo "🔄 Изменений нет, коммит не требуется"
          fi
