name: Обработка Markdown файлов из исходного репозитория

on:
  schedule:
    - cron: '0 0 * * 1'  # Запуск каждый понедельник
  workflow_dispatch:  # Позволяет запускать workflow вручную

env:
  SOURCE_OWNER: 'ciscoheat'
  SOURCE_REPO: 'superforms-web'
  SOURCE_BRANCH: 'main'

jobs:
  process-markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout нашего репозитория
        uses: actions/checkout@v4

      - name: Настройка Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
        
      - name: Создание рабочих директорий
        run: |
          mkdir -p docs
          mkdir -p /tmp/source-repo
          mkdir -p /tmp/md_processing

      - name: Клонирование исходного репозитория
        run: |
          echo "📥 Клонирование исходного репозитория..."
          git clone https://github.com/${{ env.SOURCE_OWNER }}/${{ env.SOURCE_REPO }}.git --branch ${{ env.SOURCE_BRANCH }} --single-branch /tmp/source-repo
          echo "✓ Репозиторий успешно клонирован"

      - name: Обработка Markdown файлов
        run: |
          echo "🔍 Поиск Markdown файлов в исходном репозитории..."
          
          # Находим все markdown файлы в src и подпапках исходного репозитория
          find /tmp/source-repo/src -type f -name "*.md" | while read file; do
            # Создаем уникальное имя на основе пути
            # Вырезаем префикс /tmp/source-repo/src/
            relpath=${file#"/tmp/source-repo/src/"}
            # Заменяем слэши на дефисы
            filename=$(echo "$relpath" | sed 's/\//-/g')
            
            echo "⚙️ Обработка файла: $file"
            echo "   → Будет сохранен как: $filename"
            
            # Создаём временный файл
            temp_file="/tmp/md_processing/$filename"
            
            # Удаляем скриптовый блок в начале файла
            sed '/^<script lang="ts">$/,/^<\/script>$/d' "$file" > "$temp_file"
            
            # Копируем обработанный файл в целевую директорию
            cp "$temp_file" "docs/$filename"
            
            echo "✅ Файл сохранен как: docs/$filename"
          done
          
      - name: Коммит и пуш изменений
        run: |
          # Проверяем, есть ли изменения
          if [[ -n $(git status -s docs/) ]]; then
            echo "💾 Сохранение изменений..."
            git add docs/
            git commit -m "Обновление обработанных Markdown файлов из исходного репозитория"
            git push origin HEAD:main
            echo "✅ Изменения успешно сохранены"
          else
            echo "🔄 Изменений нет, коммит не требуется"
          fi
          
      - name: Очистка
        if: always()
        run: |
          # Удаляем временные директории
          rm -rf /tmp/source-repo
          rm -rf /tmp/md_processing
          echo "🧹 Временные данные удалены"
